### ISSUE TITLE
Version 7 of class Card not hyperlinked in Exercises

### ISSUE THREAD

**Issue by nima200** [prmr/SoftwareDesign#13]
Would it be possible to hyper-link 'version 7' on the [module 1 exercises section](https://github.com/prmr/SoftwareDesign/blob/master/modules/Module-01.md#exercises) to the corresponding file to be able to complete this exercise?

**Comment by prmr** [comment]
Absolutely. All the versions are here: https://github.com/prmr/SoftwareDesign/tree/master/modules/artifacts/module-01/comp303

I will link them in my next pass through the module.
