### ISSUE TITLE
Module 2 Typos

### ISSUE THREAD

**Issue by nima200** [prmr/SoftwareDesign#16]
In [General Concepts and Definitions](https://github.com/prmr/SoftwareDesign/blob/master/modules/Module-02.md#general-concepts-and-definitions), in the second paragraph, "**A** interface to a class..." -> "**An** interface to a class..."
In [Iterating Over an Aggregation](https://github.com/prmr/SoftwareDesign/blob/master/modules/Module-02.md#iterating-over-an-aggregation), in the paragraph after the first snippet of code, "The clients of the Deck **will may** start relying on the operations..." is ambiguous. Suggestion: "will", "may", "will or may", or "will/may".
In [The Concept of Design Patterns](https://github.com/prmr/SoftwareDesign/blob/master/modules/Module-02.md#the-concept-of-design-patterns), in "...(from the author list), is one of the most influential software design **book** in existence." -> "one of the ... **books** in existence."
In [The Iterator Design Pattern](https://github.com/prmr/SoftwareDesign/blob/master/modules/Module-02.md#the-iterator-design-pattern), in the last note of the section, "...the client does not need to interact with **concrete a** iterator." -> "... **a concrete** iterator."
In [The Interface Segregation Principle](https://github.com/prmr/SoftwareDesign/blob/master/modules/Module-02.md#the-interface-segregation-principle), in the second paragraph after the second diagram, "... entire interface to the server class, or whether it should only depend on **a _role_ objects** of this class will fulfill" -> "... a _role_ **that** objects of this ...".

**Comment by prmr** [comment]
Fixed, thanks.
