### ISSUE TITLE
Wrong diagram in module 5 notes

### ISSUE THREAD

**Issue by nima200** [prmr/SoftwareDesign#20]
Hi
I noticed that this diagram was posted under the explanation of the prototype design pattern. The text is talking about the jetUML toolbar while the photo is on solitaire. Was this intentional?
![image](https://user-images.githubusercontent.com/16521944/32204458-b391eed8-bdbf-11e7-82a3-17344e1c2a2b.png)

**Comment by prmr** [comment]
Fixed, thanks for reporting this.
