### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by AllanWang** [prmr/SoftwareDesign#25]
[Overloading methods](https://github.com/prmr/SoftwareDesign/blob/master/modules/Module-07.md#overloading-methods) "support a another mechanism"

**Comment by prmr** [comment]
Fixed all M7 typos

**Comment by AllanWang** [comment]
Another one in module 7:

https://github.com/prmr/SoftwareDesign/blob/master/modules/figures/m07-abstract.png

- Po**ii**nt aPosition
